# Generated by Django 4.0.4 on 2022-05-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_image/')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
