# Generated by Django 4.0.4 on 2022-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
