# Generated by Django 4.0.4 on 2022-05-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_gallerymodel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='service_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='App_main.servicesmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='service_type',
            field=models.CharField(choices=[('Home Service', 'Home Service'), ('Go to Workshop', 'Go to Workshop')], max_length=50),
        ),
    ]
