# Generated by Django 4.0.4 on 2022-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0004_bookingmodel_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts_n_Accessories_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specifications', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
