# Generated by Django 4.0.4 on 2022-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0005_parts_n_accessories_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_n_accessories_model',
            name='price',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
