# Generated by Django 4.0.4 on 2022-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0007_parts_n_accessories_model_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='Total_cost',
            field=models.IntegerField(blank=True),
        ),
    ]
