# Generated by Django 4.0.4 on 2022-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0008_alter_bookingmodel_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('Service Processing', 'Service Processing'), ('Service Accepted', 'Service Accepted'), ('Service Confirmed', 'Service Confirmed'), ('Service Provided', 'Service Provided'), ('Service Rejected', 'Service Rejected')], default='Service Processing', max_length=20),
        ),
    ]
