# Generated by Django 4.0.4 on 2022-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
